In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
df = pd.read_csv('C:/Users/ASUS/Downloads/combined_data_count.csv')
# Selecting x variable from 5th column to 20th column
x = df.iloc[:, 4:13]  # iloc[:, start_index:end_index+1]

# Selecting y variable in 21st column
y = df.iloc[:, 14]  # iloc[:, column_index]

# If you prefer x and y as numpy arrays
x = x.values
y = y.values

In [4]:
df

YEAR  DOY        Date District  T2M_MIN  T2M_MAX    T2M  QV2M   RH2M  \
0      2020    1  01/01/2020  Udaipur    11.12    21.48  15.37  6.35  54.94   
1      2020    2  01/02/2020  Udaipur    11.96    21.07  15.69  7.51  65.12   
2      2020    3  01/03/2020  Udaipur    11.28    17.27  13.69  7.02  67.81   
3      2020    4  01/04/2020  Udaipur     9.64    16.94  12.70  7.14  73.69   
4      2020    5  01/05/2020  Udaipur     7.69    16.96  11.48  6.04  68.38   
...     ...  ...         ...      ...      ...      ...    ...   ...    ...   
71633  2023  362  12/28/2023     doti    10.12    21.44  14.33  6.29  58.19   
71634  2023  363  12/29/2023     doti     9.96    21.48  14.20  6.47  61.06   
71635  2023  364  12/30/2023     doti    10.65    20.82  14.24  5.98  55.62   
71636  2023  365  12/31/2023     doti    10.05    20.37  13.59  5.31  52.25   
71637  2024    1  01/01/2024     doti     9.82    20.36  13.25  4.82  48.44   

       PRECTOTCORR  WS10M    WD2M  GWETTOP  GWETROOT  Fire Count  
0             0.00   1.91  116.94     0.48      0.49           0  
1             0.20   1.82   80.62     0.48      0.49           0  
2             4.46   1.69  107.38     0.51      0.49           0  
3             0.53   1.96  206.69     0.49      0.49           0  
4             0.13   2.94  298.44     0.48      0.49           0  
...            ...    ...     ...      ...       ...         ...  
71633         0.00   1.73  104.25     0.55      0.57           0  
71634         0.00   1.76  118.88     0.55      0.57           0  
71635         0.00   1.46  134.94     0.55      0.56           0  
71636         0.00   1.71  118.81     0.55      0.56           0  
71637         0.00   1.64  115.19     0.55      0.56           0  

[71638 rows x 15 columns]

In [5]:
df.describe()

YEAR           DOY       T2M_MIN       T2M_MAX           T2M  \
count  71638.000000  71638.000000  71638.000000  71638.000000  71638.000000   
mean    2021.500684    183.000684     10.026620     19.666989     14.329465   
std        1.119875    105.510809     10.619677     10.137689     10.342122   
min     2020.000000      1.000000    -35.540000    -16.110000    -24.620000   
25%     2020.000000     92.000000      2.900000     12.620000      7.250000   
50%     2021.500000    183.000000     10.980000     19.820000     14.760000   
75%     2023.000000    274.000000     18.800000     27.510000     22.870000   
max     2024.000000    366.000000     32.090000     46.120000     38.200000   

               QV2M          RH2M   PRECTOTCORR         WS10M          WD2M  \
count  71638.000000  71638.000000  71638.000000  71638.000000  71638.000000   
mean       9.582710     69.339598      4.055793      2.449244    180.940449   
std        5.442958     19.297881      9.623249      0.873312     56.988881   
min        0.550000      7.000000      0.000000      0.620000      7.620000   
25%        5.190000     55.190000      0.000000      1.910000    136.440000   
50%        8.420000     73.250000      0.290000      2.300000    175.810000   
75%       13.240000     86.120000      4.230000      2.740000    222.620000   
max       23.500000    100.000000    377.840000     15.080000    345.880000   

            GWETTOP      GWETROOT    Fire Count  
count  71638.000000  71638.000000  71638.000000  
mean       0.651097      0.646985      0.123426  
std        0.183044      0.166530      0.986944  
min        0.090000      0.340000      0.000000  
25%        0.520000      0.510000      0.000000  
50%        0.670000      0.630000      0.000000  
75%        0.800000      0.780000      0.000000  
max        1.000000      1.000000     43.000000

In [6]:
x

array([[ 11.12,  21.48,  15.37, ...,   1.91, 116.94,   0.48],
       [ 11.96,  21.07,  15.69, ...,   1.82,  80.62,   0.48],
       [ 11.28,  17.27,  13.69, ...,   1.69, 107.38,   0.51],
       ...,
       [ 10.65,  20.82,  14.24, ...,   1.46, 134.94,   0.55],
       [ 10.05,  20.37,  13.59, ...,   1.71, 118.81,   0.55],
       [  9.82,  20.36,  13.25, ...,   1.64, 115.19,   0.55]])

In [7]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [8]:
df.shape

(71638, 15)

In [10]:
df.head(10)

YEAR  DOY        Date District  T2M_MIN  T2M_MAX    T2M  QV2M   RH2M  \
0  2020    1  01/01/2020  Udaipur    11.12    21.48  15.37  6.35  54.94   
1  2020    2  01/02/2020  Udaipur    11.96    21.07  15.69  7.51  65.12   
2  2020    3  01/03/2020  Udaipur    11.28    17.27  13.69  7.02  67.81   
3  2020    4  01/04/2020  Udaipur     9.64    16.94  12.70  7.14  73.69   
4  2020    5  01/05/2020  Udaipur     7.69    16.96  11.48  6.04  68.38   
5  2020    6  01/06/2020  Udaipur     6.67    18.37  11.44  5.19  59.50   
6  2020    7  01/07/2020  Udaipur     8.48    19.69  12.90  5.13  53.44   
7  2020    8  01/08/2020  Udaipur     9.73    18.65  13.48  6.35  62.38   
8  2020    9  01/09/2020  Udaipur     8.88    15.99  12.07  7.45  80.25   
9  2020   10  01/10/2020  Udaipur     7.50    18.21  11.68  6.71  75.44   

   PRECTOTCORR  WS10M    WD2M  GWETTOP  GWETROOT  Fire Count  
0         0.00   1.91  116.94     0.48      0.49           0  
1         0.20   1.82   80.62     0.48      0.49           0  
2         4.46   1.69  107.38     0.51      0.49           0  
3         0.53   1.96  206.69     0.49      0.49           0  
4         0.13   2.94  298.44     0.48      0.49           0  
5         0.00   1.96  270.75     0.48      0.49           0  
6         0.03   2.11  287.62     0.48      0.49           0  
7         0.90   1.52  149.81     0.48      0.49           0  
8         2.78   1.95  190.31     0.50      0.49           0  
9         0.09   3.26  292.25     0.48      0.49           0

In [11]:
df = df.drop_duplicates()

# Now 'df' contains the DataFrame with duplicate rows removed

# Optionally, you can reset the index if you want
df = df.reset_index(drop=True)

# Print the DataFrame after removing duplicates
print("DataFrame after removing duplicates:")
print(df)

DataFrame after removing duplicates:
       YEAR  DOY        Date District  T2M_MIN  T2M_MAX    T2M  QV2M   RH2M  \
0      2020    1  01/01/2020  Udaipur    11.12    21.48  15.37  6.35  54.94   
1      2020    2  01/02/2020  Udaipur    11.96    21.07  15.69  7.51  65.12   
2      2020    3  01/03/2020  Udaipur    11.28    17.27  13.69  7.02  67.81   
3      2020    4  01/04/2020  Udaipur     9.64    16.94  12.70  7.14  73.69   
4      2020    5  01/05/2020  Udaipur     7.69    16.96  11.48  6.04  68.38   
...     ...  ...         ...      ...      ...      ...    ...   ...    ...   
71633  2023  362  12/28/2023     doti    10.12    21.44  14.33  6.29  58.19   
71634  2023  363  12/29/2023     doti     9.96    21.48  14.20  6.47  61.06   
71635  2023  364  12/30/2023     doti    10.65    20.82  14.24  5.98  55.62   
71636  2023  365  12/31/2023     doti    10.05    20.37  13.59  5.31  52.25   
71637  2024    1  01/01/2024     doti     9.82    20.36  13.25  4.82  48.44   

       PRECTOT

In [12]:
df.shape

(71638, 15)

In [13]:
df.isnull().sum()

YEAR           0
DOY            0
Date           0
District       0
T2M_MIN        0
T2M_MAX        0
T2M            0
QV2M           0
RH2M           0
PRECTOTCORR    0
WS10M          0
WD2M           0
GWETTOP        0
GWETROOT       0
Fire Count     0
dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 42)
#85:15 traning:test split ratio

In [15]:
print(X_train)

[[ -0.3    9.48   3.59 ...   1.87 176.38   0.55]
 [ 15.62  22.89  18.83 ...   2.3  230.31   0.66]
 [  4.08  14.07   8.65 ...   2.45 213.94   0.52]
 ...
 [  9.8   21.59  15.11 ...   2.42 134.5    0.56]
 [ 21.45  31.05  26.19 ...   2.34 145.     0.48]
 [ 13.32  21.33  16.99 ...   1.38 131.31   0.49]]


In [16]:
print(y_train)

[0 0 0 ... 0 0 0]


In [17]:
len(y_train)

57310

In [18]:
len(X_test)

14328

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#fitting our training and test set into the object sc 
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.svm import SVR
regressor1 = SVR(kernel = 'rbf')
regressor1.fit(X_train, y_train)

In [17]:
y_pred = regressor1.predict(X_test)
y_pred

array([70.45955959, 65.95255838, 59.24072749, 62.05997157, 64.03268734,
       63.01668146, 57.79930368, 64.90535812, 65.16071155, 69.25481389,
       63.28784068, 60.64303517, 58.06856534, 63.38119587, 59.94930761,
       58.98272676, 60.52329341, 56.27024376, 57.94658066, 60.64010563,
       56.74502289, 58.72504253, 59.83452044, 56.57026665, 58.4127311 ,
       58.04378679, 59.10311904, 69.09173286, 62.33239771, 61.99421911,
       63.02284768, 63.25395855, 64.59319321, 62.32038832, 58.73536715,
       60.73741572, 64.49610842, 57.79686192, 59.16013091, 57.79684343,
       58.73694607, 62.91935239, 64.38646724, 61.34902172, 62.54569665,
       61.01737378, 61.87233674, 59.28882133, 65.36512399, 65.59957924,
       56.40176364, 62.04330409, 60.84659663, 57.26347784, 57.35164227,
       57.12910449, 64.57831204, 62.39288414, 61.9856547 , 62.35702372,
       58.21378164, 59.43021894, 61.40390067, 62.61959492, 59.92757637,
       65.55035028, 64.50538769, 62.2270247 , 57.43196629, 60.05